#!/usr/bin/perl --
# Free replacement for Sun's insert_brackets as required by Openwin's
# text_extras_menu.
#
# Copyright (C) 1998 by Martin Buck <mbuck@debian.org>
# Licensed under the GNU General Public License

if ($#ARGV != 1) {
  die "Usage: $0 <left> <right>\n";
}

print "$ARGV[0]";
while (<STDIN>) {
  print $_;
}
print "$ARGV[1]";
