#!/bin/sh

# Running olvwm directly through the x-window-manager link seems to cause
# problems, because the program name is used to find certain resources.
# So we let x-window-manager point to this wrapper and then exec olvwm with
# its real name.

exec /usr/bin/olvwm "$@"
